[project]
name = "swiss-army-upload"
version = "0.1.0"
description = ""
authors = [
    {name = "Jamie Bliss",email = "jamie@teahouse.cafe"}
]
readme = "README.md"
requires-python = ">=3.14,<4.0"
dependencies = [
    "anyio[trio] (>=4.12.0,<5.0.0)",
    "httpx[http2] (>=0.28.1,<0.29.0)",
    "handtruck (<0.2.0)",
    "dykes @ git+https://github.com/AstraLuma/dykes.git@subcommands",
    "keyring (>=25.7.0,<26.0.0)",
    "bitwarden-keyring (>=0.3.1,<0.4.0)",
    "onepassword-keyring (>=0.1.1,<0.2.0)",
    "saucer @ git+https://github.com/AstraLuma/svcs.git@saucer",
]

[project.scripts]
swiss-army-upload = 'swiss_army_upload:entrypoint'
sau = 'swiss_army_upload:entrypoint'

[tool.poetry]
packages = [
    {include = "swiss_army_upload", from = "src"}
]

[project.entry-points."swiss_army_upload.backend"]
# Teahouse Hosting, https://teahouse.cafe/
tea = "swiss_army_upload.backends.teahouse:TeahouseBackend"
# Git Pages, https://git-pages.org/
page = "swiss_army_upload.backends.gitpages"
# Nekoweb, https://nekoweb.org/
neko = "swiss_army_upload.backends.nekoweb"
# Neocities, https://neocities.org/
neo = "swiss_army_upload.backends.neocities"

[tool.mypy]
check_untyped_defs = true

[[tool.mypy.overrides]]
module = ["aws_request_signer.*"]
follow_untyped_imports = true

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"



# content below this line added by briefcase convert
# This project was generated with 0.3.25 using template: https://github.com/beeware/briefcase-template @ v0.3.25
[tool.briefcase]
project_name = "Swiss Army Upload"
bundle = "cafe.teahouse"
version = "0.0.1"
url = "https://codeberg.org/teahouse/swiss-army-upload"
license.file = "LICENSE"
author = "Jamie Bliss"
author_email = "jamie@teahouse.cafe"

[tool.briefcase.app.swiss-army-upload]
formal_name = "Swiss Army Upload"
description = ""
long_description = """More details about the app should go here.
"""
sources = [
    "src/swiss_army_upload",
]
test_sources = [
    "tests",
]
console_app = true

requires = [
    # Add your cross-platform app requirements here
]
test_requires = [
    # Add your cross-platform test requirements here
]

[tool.briefcase.app.swiss-army-upload.macOS]
universal_build = true
requires = [
    # Add your macOS-specific app requirements here
]

[tool.briefcase.app.swiss-army-upload.linux]
requires = [
    # Add your Linux-specific app requirements here
]

[tool.briefcase.app.swiss-army-upload.linux.system.debian]
system_requires = [
    # Add any system packages needed at build the app here
]

system_runtime_requires = [
    # Add any system packages needed at runtime here
]

[tool.briefcase.app.swiss-army-upload.linux.system.rhel]
system_requires = [
    # Add any system packages needed at build the app here
]

system_runtime_requires = [
    # Add any system packages needed at runtime here
]

[tool.briefcase.app.swiss-army-upload.linux.system.suse]
system_requires = [
    # Add any system packages needed at build the app here
]

system_runtime_requires = [
    # Add any system packages needed at runtime here
]

[tool.briefcase.app.swiss-army-upload.linux.system.arch]
system_requires = [
    # Add any system packages needed at build the app here
]

system_runtime_requires = [
    # Add any system packages needed at runtime here
]

[tool.briefcase.app.swiss-army-upload.linux.flatpak]
flatpak_runtime = "org.freedesktop.Platform"
flatpak_runtime_version = "24.08"
flatpak_sdk = "org.freedesktop.Sdk"

[tool.briefcase.app.swiss-army-upload.windows]
requires = [
    # Add your Windows-specific app requirements here
]

# Mobile deployments
[tool.briefcase.app.swiss-army-upload.iOS]
supported = false

[tool.briefcase.app.swiss-army-upload.android]
supported = false

# Web deployments
[tool.briefcase.app.swiss-army-upload.web]
supported = false


[dependency-groups]
dev = [
    "mypy (>=1.19.0,<2.0.0)",
    "pytest (>=9.0.2,<10.0.0)",
    "httpx[http2] (>=0.28.1,<0.29.0)",
    "keyrings-alt (>=5.0.2,<6.0.0)"
]
