[project]
name = "swiss-army-upload"
dynamic = ["version"]
description = "Interact with multiple web hosts"
authors = [
    {name = "Jamie Bliss",email = "jamie@teahouse.cafe"}
]
readme = "README.md"
requires-python = ">=3.12,<4.0"
dependencies = [
    "anyio[trio] (>=4.12.0,<5.0.0)",
    "httpx[http2] (>=0.28.1,<0.29.0)",
    "handtruck (>=0.3.2)",
    "keyring (>=25.7.0,<26.0.0)",
    # Doesn't implement get_credential(), so useless to us
    # "bitwarden-keyring (>=0.3.1,<0.4.0)",
    # Incorrectly implements get_credential()
    # "onepassword-keyring (>=0.1.1,<0.2.0)",
    "svcs",
    "platformdirs (>=4.5.1,<5.0.0)",
    "rich (>=14.2.0,<15.0.0)",
    "httpdate (>=1.2.0,<2.0.0)",
]

[project.urls]
source = "https://codeberg.org/teahouse/swiss-army-upload"
docs = "https://swiss-army-upload.teahouse.cafe"

[project.scripts]
swiss-army-upload = 'swiss_army_upload:entrypoint'
sau = 'swiss_army_upload:entrypoint'

[project.entry-points."swiss_army_upload.backend"]
# Teahouse Hosting, https://teahouse.cafe/
tea = "swiss_army_upload.backends.teahouse:TeahouseBackend"
# Git Pages, https://git-pages.org/
pages = "swiss_army_upload.backends.gitpages:GitPagesBackend"
# Nekoweb, https://nekoweb.org/
# neko = "swiss_army_upload.backends.nekoweb"
# Neocities, https://neocities.org/
# neo = "swiss_army_upload.backends.neocities"

[dependency-groups]
dev = [
    "mypy (>=1.19.0,<2.0.0)",
    "pytest (>=9.0.2,<10.0.0)",
    "httpx[http2] (>=0.28.1,<0.29.0)",
    "keyrings-alt (>=5.0.2,<6.0.0)",
    "starlette (>=0.52.1,<0.53.0)",
    "pytest-ephemeral-container (>=0.3.0)",
]
docs = [
    "sphinx (>=9.1.0,<10.0.0)",
    "sphinxext-opengraph[social-cards] (>=0.13.0,<0.14.0)",
    "sphinx-autobuild (>=2025.8.25,<2026.0.0)",
    "sphinx-rtd-theme (>=3.1.0,<4.0.0)",
    "sphinx-inline-tabs (>=2025.12.21.14,<2026.0.0.0)"
]

[tool.poetry]
packages = [
    {include = "swiss_army_upload", from = "src"},
    {include = "scr.py", from = "src"},
]
version = "0.0.0"

[tool.poetry.requires-plugins]
poetry-dynamic-versioning = { version = ">=1.0.0,<2.0.0", extras = ["plugin"] }

[tool.poetry-dynamic-versioning]
enable = true
bump = true
metadata = false

[tool.mypy]
check_untyped_defs = true

[[tool.mypy.overrides]]
module = ["aws_request_signer.*"]
follow_untyped_imports = true

[[tool.mypy.overrides]]
module = ["keyrings.*"]
follow_untyped_imports = true

[tool.pytest.ini_options]
anyio_mode = "auto"
required_plugins = ["anyio"]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0", "poetry-dynamic-versioning>=1.0.0,<2.0.0"]
build-backend = "poetry.core.masonry.api"

# content below this line added by briefcase convert
# This project was generated with 0.3.25 using template: https://github.com/beeware/briefcase-template @ v0.3.25
[tool.briefcase]
project_name = "Swiss Army Upload"
bundle = "cafe.teahouse"
# version = "0.0.1"
url = "https://codeberg.org/teahouse/swiss-army-upload"
license.file = "LICENSE"
author = "Jamie Bliss"
author_email = "jamie@teahouse.cafe"

[tool.briefcase.app.swiss-army-upload]
formal_name = "Swiss Army Upload"
description = "Interact with multiple web hosts"
long_description = """Uploads/downloads files with multiple web hosts:
* Teahouse Hosting
* Git Pages (soon)
* Neocities (soon)
* Nekoweb (soon)
"""
sources = [
    "src/swiss_army_upload",
]
test_sources = [
    "tests",
]
console_app = true

requires = [
    # Add your cross-platform app requirements here
]
test_requires = [
    # Add your cross-platform test requirements here
]

[tool.briefcase.app.swiss-army-upload.macOS]
universal_build = true
requires = [
    # Add your macOS-specific app requirements here
]

[tool.briefcase.app.swiss-army-upload.linux]
requires = [
    # Add your Linux-specific app requirements here
]

[tool.briefcase.app.swiss-army-upload.linux.system.debian]
system_requires = [
    # Add any system packages needed at build the app here
]

system_runtime_requires = [
    # Add any system packages needed at runtime here
]

[tool.briefcase.app.swiss-army-upload.linux.system.rhel]
system_requires = [
    # Add any system packages needed at build the app here
]

system_runtime_requires = [
    # Add any system packages needed at runtime here
]

[tool.briefcase.app.swiss-army-upload.linux.system.suse]
system_requires = [
    # Add any system packages needed at build the app here
]

system_runtime_requires = [
    # Add any system packages needed at runtime here
]

[tool.briefcase.app.swiss-army-upload.linux.system.arch]
system_requires = [
    # Add any system packages needed at build the app here
]

system_runtime_requires = [
    # Add any system packages needed at runtime here
]

[tool.briefcase.app.swiss-army-upload.linux.flatpak]
flatpak_runtime = "org.freedesktop.Platform"
flatpak_runtime_version = "24.08"
flatpak_sdk = "org.freedesktop.Sdk"

[tool.briefcase.app.swiss-army-upload.windows]
requires = [
    # Add your Windows-specific app requirements here
]

# Mobile deployments
[tool.briefcase.app.swiss-army-upload.iOS]
supported = false

[tool.briefcase.app.swiss-army-upload.android]
supported = false

# Web deployments
[tool.briefcase.app.swiss-army-upload.web]
supported = false
