name: test

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]
  workflow_dispatch:

jobs:
  pytest:
    runs-on: docker-build
    strategy:
      matrix:
        # Based on https://versions.do1g.com/
        python-version: ['3.12', '3.13', '3.14']
    steps:
      - name: checkout-code
        uses: https://data.forgejo.org/actions/checkout@v4
      - name: install poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
      - name: install python
        uses: https://github.com/actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'
      - run: poetry install
      - name: run tests
        run: |
          poetry run pytest --verbose

  mypy:
    runs-on: codeberg-tiny
    steps:
      - name: checkout-code
        uses: https://data.forgejo.org/actions/checkout@v4
      - name: install poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
      - name: install python
        uses: https://github.com/actions/setup-python@v6
        with:
          cache: 'poetry'
          python-version: "3.14"
      - run: poetry install
      - name: type check
        run: |
          poetry run mypy src tests
