name: Publish Packages

on:
  schedule:
    - cron: '36 0 * * *'
  push:
    branches: [ "trunk" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "trunk" ]
  workflow_dispatch:

env:
  # Use ourselves
  REGISTRY: codeberg.org
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  container:
    runs-on: docker-build
    permissions:
      contents: read
      # Doesn't do anything yet
      # https://codeberg.org/forgejo/forgejo/issues/3571
      # packages: write

    steps:
      - name: Checkout repository
        uses: https://data.forgejo.org/actions/checkout@v4

      # Set up BuildKit Docker container builder to be able to build
      # multi-platform images and export cache
      - name: Set up Docker Buildx
        uses: https://github.com/docker/setup-buildx-action@v3.0.0

      # Login against a Docker registry except on PR
      - name: Log into registry
        if: github.event_name != 'pull_request'
        uses: https://github.com/docker/login-action@v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ vars.PAT_USER }}
          password: ${{ secrets.PAT_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      - name: Extract Docker metadata
        id: meta
        uses: https://github.com/docker/metadata-action@v5.0.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # Build and push Docker image with Buildx (don't push on PR)
      - name: Build and push Docker image
        id: build-and-push
        uses: https://github.com/docker/build-push-action@v5.0.0
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  pypi:
    runs-on: codeberg-small-lazy
    if: forgejo.event_name != 'schedule'
    permissions:
      contents: read
      # Doesn't do anything yet
      # https://codeberg.org/forgejo/forgejo/issues/3571
      # packages: write

    steps:
      - name: Checkout repository
        uses: https://data.forgejo.org/actions/checkout@v4
        with:
          fetch-depth: 0
      - name: install poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
      - run: poetry install
      - run: poetry build
      - name: configure registry
        if: forgejo.event_name == 'push' && startsWith(forgejo.ref, 'refs/tags/')
        run: |
          poetry config repositories.codeberg https://codeberg.org/api/packages/teahouse/pypi
          poetry config http-basic.codeberg ${{ vars.PAT_USER }} ${{ secrets.PAT_TOKEN }}
      - name: poetry publish
        if: forgejo.event_name == 'push' && startsWith(forgejo.ref, 'refs/tags/')
        run: poetry publish --no-interaction --repository=codeberg
