name: Runner Debug

# This workflow uses actions that are not certified by GitHub.
on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]
  workflow_dispatch:


jobs:
  build:
    runs-on: docker-build

    steps:
      - name: env vars
        run: env|sort
      - name: mounts
        run: mount
      - name: docker
        run: docker info
