set windows-powershell := true
set fallback

SPHINXOPTS    := ""
SOURCEDIR     := "."
BUILDDIR      := "_build"

# Show this help
@help:
  just --list

# Run sphinx autobuild against the docs.
serve:
  poetry run sphinx-autobuild --nitpicky --port 0 --open-browser --watch "../src" "{{SOURCEDIR}}" "{{BUILDDIR}}/html"

# Do a sphinx build
build KIND="html":
  poetry run sphinx-build -M {{KIND}} "{{SOURCEDIR}}" "{{BUILDDIR}}" {{SPHINXOPTS}}

# Clean up built files
@clean:
  just build clean
